# ═══════════════════════════════════════════════════════════════════════════
#                           APPLICATION CONFIGURATION
# ═══════════════════════════════════════════════════════════════════════════


application_settings:
  threads: 500
  keepalive_interval: 600 # seconds
  database_url: "sqlite://database/database.sqlite3" # SQlite or postgres, e.g. sqlite://database.db or postgres://user:password@localhost/dbname
  skip_logged_accounts: true
  shuffle_accounts: true
  check_uniqueness_of_proxies: true
  disable_auto_proxy_change: true # disable automatic proxy change for farming (for example for ISP proxy)


attempts_and_delay_settings:
  delay_before_start:
    min: 5 # seconds
    max: 20 # seconds

  error_delay: 5 # seconds
  max_register_attempts: 10
  max_login_attempts: 5
  max_stats_attempts: 3
  max_tasks_attempts: 3
  max_attempts_to_receive_app_id: 3
  max_attempts_to_verify_email: 10
  max_attempts_to_send_keepalive: 3


captcha_settings:
  captcha_service: "2captcha"           # Options: "anticaptcha" or "2captcha"
  max_captcha_solving_time: 60            # Time in seconds

  two_captcha_api_key: "323612aa7e63bb0f675c21eba9d2894b"


redirect_settings:
  enabled: true
  email: "alextop135@icloud.com"
  password: "cyvg-gxay-iqth-vulp"
  imap_server: "imap.mail.me.com"
  use_proxy: false


imap_settings:
  use_proxy_for_imap: false

  use_single_imap:
    enable: true
    imap_server: "imap.mail.me.com"

  servers:
    gmail.com: imap.gmail.com
    yahoo.com: imap.mail.yahoo.com
    icloud.com: imap.mail.me.com
    mail.ru: imap.mail.ru
    gmx.com: imap.gmx.com
    gmx.net: imap.gmx.net
    gmx.de: imap.gmx.net
    onet.pl: imap.poczta.onet.pl
    onet.com.pl: imap.poczta.onet.pl
    op.pl: imap.poczta.onet.pl
    onet.eu: imap.poczta.onet.pl
    gazeta.pl: imap.gazeta.pl
    firemail.eu: imap.firemail.de
